version: '3'
services:
  python:
    image: ${OWNER}/${NAME}:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    network_mode: host
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DYNAMODB_HOST: ${DYNAMODB_HOST}
      DYNAMODB_PORT: ${DYNAMODB_PORT}
      DYNAMODB_TABLE_PREFIX: ${DYNAMODB_TABLE_PREFIX}
      DYNAMODB_MOCK: ${DYNAMODB_MOCK}
      APP_ENV: ${APP_ENV}
      SKIP_SLOW: ${SKIP_SLOW}
